### ISSUE TITLE
Вече

### ISSUE THREAD

**Issue by bnmsdf** [fikfok/homeland-party#1]
Сделать так, что бы при клике на количестве участников в десятке на странице "Вступить в географиескую десятку" отображалось модальное окно с перечнем участников

**Comment by fikfok** [comment]
Взял в работу.

**Comment by fikfok** [comment]
Сделал.
Теперь количество уастников отображается в виде кликабельного бейджа. При нажатии возникает модальное окно, где можно кликнуть на каждого участника и перейти в его карточку.
